### ISSUE TITLE
[design]로그인 페이지 퍼블리싱

### ISSUE THREAD

**Issue by yellowmodric** [Summer-Bootcamp-2024/SML-Frontend#4]
##📌 퍼블리싱 할 내용 or 수정할 내용
로그인 페이지 퍼블리싱

![image](https://github.com/Summer-Bootcamp-2024/SML-Frontend/assets/87848941/0af35b11-bf3b-4199-b4ff-7060d2894e1f)

**Comment by heesu52** [comment]
이슈에 [태그]뒤에 어떤 내용 구현하는지 작성해주시면 좋습니다:)
